"""delete cascade on chapters

Revision ID: f455a170bb7c
Revises: 430e7e66aaf6
Create Date: 2023-04-23 10:24:34.351141

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'f455a170bb7c'
down_revision = '430e7e66aaf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.alter_column('story_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    if environment == "production":
        op.execute(f"ALTER TABLE tags SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.alter_column('story_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
