"""migrateee

Revision ID: 430e7e66aaf6
Revises: c56d0f55df19
Create Date: 2023-04-21 21:28:11.598453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430e7e66aaf6'
down_revision = 'c56d0f55df19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###